curl -x POST -H "Content-Type: application/json" \
    -d '{"_id":{"$oid":"62750d9138fc0637ac537697"},"name":"a","schedule":"ba","start_date":"2022-04-24","end_date":"2022-05-20"}' \
    http://localhost:3030/insGroup